# Generated by Django 2.2 on 2023-01-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipality'),
        ),
    ]
